// <auto-generated />
using Animal_Shelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Animal_Shelter.Migrations
{
    [DbContext(typeof(Animal_ShelterContext))]
    [Migration("20221028200912_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Animal_Shelter.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            Age = 1,
                            Name = "Tom",
                            Sex = "Male"
                        },
                        new
                        {
                            CatId = 2,
                            Age = 5,
                            Name = "Spot",
                            Sex = "Male"
                        },
                        new
                        {
                            CatId = 3,
                            Age = 5,
                            Name = "Kuki",
                            Sex = "Female"
                        },
                        new
                        {
                            CatId = 4,
                            Age = 4,
                            Name = "Pichy",
                            Sex = "Male"
                        },
                        new
                        {
                            CatId = 5,
                            Age = 3,
                            Name = "Lola",
                            Sex = "Female"
                        });
                });

            modelBuilder.Entity("Animal_Shelter.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Age = 3,
                            Name = "Goofy",
                            Sex = "Male"
                        },
                        new
                        {
                            DogId = 2,
                            Age = 2,
                            Name = "Luna",
                            Sex = "Female"
                        },
                        new
                        {
                            DogId = 3,
                            Age = 1,
                            Name = "Tobias",
                            Sex = "Male"
                        },
                        new
                        {
                            DogId = 4,
                            Age = 9,
                            Name = "Rumbo",
                            Sex = "Male"
                        },
                        new
                        {
                            DogId = 5,
                            Age = 8,
                            Name = "Pluto",
                            Sex = "Male"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
